# Identify a problem that can be solved by creating a function in R.
# Write test cases for that function in test-believe.R, instead of creating the
# function yourself.

# Use a large language model, like ChatGPT or cs50.ai, to implement the function
# for you. Modify the code as needed to pass your test cases.
# Because you’ll be relying on a large language model to generate code for you,
# it’s most important to focus on writing thorough test cases.


# Function generated by ChatGPT
calculate_bmi <- function(weight_kg, height_m) {
  if(!is.numeric(weight_kg) | !is.numeric(height_m)) {
    stop("Weight and height must be integers or floats")
  } else if (weight_kg < 0 | height_m < 0) {
    stop("Weight and height must be positive values.")
  } else if (weight_kg >= 200 | height_m > 2.5) {
    warning("Please enter reasonable height and weight values.")
  } else if (weight_kg == 0 | height_m == 0) {
    warning("You are non-existent")
  } else {
    bmi <- weight_kg / (height_m ^ 2)
    return (round(bmi, 2))
  }
}